# Extra autostart processes
# exec-once = uwsm app -- my-service
exec-once = $HOME/.config/waybar/scripts/waybar-timer/target/release/waybar_timer serve
exec-once = uair

# Remap mouse buttons
exec-once = input-remapper-autoload
